### ISSUE TITLE
screen Recorder does not work

### ISSUE THREAD

**Issue by Raj123456788** [javaing/android_screen_recorder#1]
Please tell me how to use it?

**Comment by javaing** [comment]
sorry, its only Chinese version UI.
it will call our company RESTful API to get the match schedule, then the game time, my background service will auto launch WebView Activity.

**Comment by Raj123456788** [comment]
Hi, I am stuck with mediaprojection error when I call capturer.start() since 4 days. Can you please recommend solution https://stackoverflow.com/questions/61276730/media-projections-require-a-foreground-service-of-type-serviceinfo-foreground-se#:~:text=You%20have%20to%20start%20a,after%20you%20start%20the%20service. I haave tried it all but still same problem.

**Comment by javaing** [comment]
> Hi, I am stuck with mediaprojection error when I call capturer.start() since 4 days. Can you please recommend solution https://stackoverflow.com/questions/61276730/media-projections-require-a-foreground-service-of-type-serviceinfo-foreground-se#:~:text=You%20have%20to%20start%20a,after%20you%20start%20the%20service. I haave tried it all but still same problem.

**Comment by javaing** [comment]
according that stackoverflow , the method of get MediaProjectionManager is different from my way, 
`manager = ctx.getSystemService(Context.MEDIA_PROJECTION_SERVICE) as MediaProjectionManager`
maybe try this way?
